export const example_shows = [
  {
    adult: false,
    backdrop_path: '/mFy2U5HVQ81hewd68897llwkwlc.jpg',
    genre_ids: [16, 10759, 10765],
    id: 60572,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ポケットモンスター',
    overview:
      'Join Ash accompanied by his partner Pikachu, as he travels through many regions, meets new friends and faces new challenges on his quest to become a Pokémon Master.',
    popularity: 377.595,
    poster_path: '/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg',
    first_air_date: '1997-04-01',
    name: 'Pokémon',
    vote_average: 7.898,
    vote_count: 1895,
    user_rating: 5,
    order_index: 0,
  },
  {
    adult: false,
    backdrop_path: '/PJSgscE4Es0TXmgIqp3X6ey8Ux.jpg',
    genre_ids: [16, 10762, 35],
    id: 1546,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Recess',
    overview:
      'Join a group of six fourth-grade best friends at Third Street Elementary School on their fun-filled adventures in their school playground. Through the ups-and-downs of adolescence, they must wrestle with authority, avoid the school snitch, and try their best to win at kick-ball.',
    popularity: 62.483,
    poster_path: '/nRKCxiZROeNaC5H80hVqSqWMYZr.jpg',
    first_air_date: '1997-09-13',
    name: 'Recess',
    vote_average: 7.7,
    vote_count: 477,
    user_rating: 4,
    order_index: 1,
  },
  {
    adult: false,
    backdrop_path: '/3MY7hMWrJ13Xtb1Y4jd7tztyPaZ.jpg',
    genre_ids: [16, 35, 10751],
    id: 387,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'SpongeBob SquarePants',
    overview:
      "Deep down in the Pacific Ocean in the subterranean city of Bikini Bottom lives a square yellow sponge named SpongeBob SquarePants. SpongeBob lives in a pineapple with his pet snail, Gary, loves his job as a fry cook at the Krusty Krab, and has a knack for getting into all kinds of trouble without really trying. When he's not getting on the nerves of his cranky next door neighbor Squidward, SpongeBob can usually be found smack in the middle of all sorts of strange situations with his best buddy, the simple yet lovable starfish, Patrick, or his thrill-seeking surfer-girl squirrel pal, Sandy Cheeks.",
    popularity: 33.043,
    poster_path: '/amvtZgiTty0GHIgD56gpouBWrcy.jpg',
    first_air_date: '1999-05-01',
    name: 'SpongeBob SquarePants',
    vote_average: 7.666,
    vote_count: 2979,
    user_rating: 4,
    order_index: 0,
  },
  {
    adult: false,
    backdrop_path: '/kU98MbVVgi72wzceyrEbClZmMFe.jpg',
    genre_ids: [16, 10759, 10765],
    id: 246,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Avatar: The Last Airbender',
    overview:
      'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
    popularity: 63.674,
    poster_path: '/v2vn1coUMPKw0GI1KGC5J4IXtqp.jpg',
    first_air_date: '2005-02-21',
    name: 'Avatar: The Last Airbender',
    vote_average: 8.7,
    vote_count: 4212,
    user_rating: 3,
    order_index: 0,
  },
  {
    adult: false,
    backdrop_path: '/1Cn0f74pZISsqC3AvxRXtN7NXMJ.jpg',
    genre_ids: [16, 35, 10765, 10762],
    id: 4630,
    origin_country: ['US', 'CA'],
    original_language: 'en',
    original_name: 'The Fairly OddParents',
    overview:
      'The zany, fast-paced adventures of a 10-year-old boy and his fairy godparents, who inadvertently create havoc as they grant wishes for their pint-sized charge.',
    popularity: 148.482,
    poster_path: '/3ryMj7tIvVtiXyI2tLvHYTjOjq4.jpg',
    first_air_date: '2001-03-30',
    name: 'The Fairly OddParents',
    vote_average: 7.6,
    vote_count: 986,
    user_rating: 3,
    order_index: 1,
  },
  {
    adult: false,
    backdrop_path: '/6neiLkVRYIVbbRTLhlSLtt8o5di.jpg',
    genre_ids: [10751, 16, 35, 10762],
    id: 537,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Hey Arnold!',
    overview:
      'The daily life of Arnold--a fourth-grader with a wild imagination, street smarts and a head shaped like a football.',
    popularity: 94.537,
    poster_path: '/c1Yv042okfvMdT1Ulwlat9Tj70B.jpg',
    first_air_date: '1996-10-07',
    name: 'Hey Arnold!',
    vote_average: 8.029,
    vote_count: 910,
    user_rating: 3,
    order_index: 0,
  },
  {
    adult: false,
    backdrop_path: '/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    genre_ids: [16, 10759, 10765],
    id: 85937,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '鬼滅の刃',
    overview:
      'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
    popularity: 74.597,
    poster_path: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    first_air_date: '2019-04-06',
    name: 'Demon Slayer: Kimetsu no Yaiba',
    vote_average: 8.652,
    vote_count: 6549,
    user_rating: 2,
    order_index: 1,
  },
  {
    adult: false,
    backdrop_path: '/wyspZaGs7CXceV3Ct7NJhcKNDkn.jpg',
    genre_ids: [35, 80],
    id: 48891,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Brooklyn Nine-Nine',
    overview:
      'A single-camera ensemble comedy following the lives of an eclectic group of detectives in a New York precinct, including one slacker who is forced to shape up when he gets a new boss.',
    popularity: 256.188,
    poster_path: '/qYjAdP0n62dJ9WLl8WGeQj7CGPH.jpg',
    first_air_date: '2013-09-17',
    name: 'Brooklyn Nine-Nine',
    vote_average: 8.215,
    vote_count: 3428,
    user_rating: 2,
    order_index: 2,
  },
];